<<<<<<< HEAD
// Supabase Database Types - Placeholder
// This would normally be generated by supabase gen types

/**
 * Lore fragment category types
 */
export type LoreCategory =
  | 'magic_system'
  | 'geography'
  | 'history'
  | 'character'
  | 'creature'
  | 'artifact'
  | 'library_text'
  | 'user_creation';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          academy_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      creations: {
        Row: {
          id: string
          title: string
          description: string | null
          type: string
          media_url: string | null
          thumbnail_url: string | null
          user_id: string
          luminor_id: string | null
          visibility: string
          status: string
          tags: string[]
          embedding: number[] | null
          likes_count: number
          comments_count: number
          views_count: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['creations']['Row'], 'id' | 'created_at' | 'updated_at' | 'likes_count' | 'comments_count' | 'views_count'>
        Update: Partial<Database['public']['Tables']['creations']['Insert']>
      }
      luminor_bonds: {
        Row: {
          id: string
          user_id: string
          luminor_id: string
          level: number
          xp: number
          relationship_type: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['luminor_bonds']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['luminor_bonds']['Insert']>
      }
      lore_fragments: {
        Row: {
          id: string
          category: LoreCategory
          title: string
          content: string
          embedding: number[] | null
          source_file: string | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['lore_fragments']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['lore_fragments']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      match_lore: {
        Args: {
          query_embedding: string
          match_threshold: number
          match_count: number
        }
        Returns: Array<{
          id: string
          content: string
          similarity: number
        }>
      }
    }
    Enums: {
      lore_category: LoreCategory
    }
  }
}
=======
// Supabase Database Types - Placeholder
// This would normally be generated by supabase gen types

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          academy_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      creations: {
        Row: {
          id: string
          title: string
          description: string | null
          type: string
          media_url: string | null
          thumbnail_url: string | null
          user_id: string
          luminor_id: string | null
          visibility: string
          status: string
          tags: string[]
          likes_count: number
          comments_count: number
          views_count: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['creations']['Row'], 'id' | 'created_at' | 'updated_at' | 'likes_count' | 'comments_count' | 'views_count'>
        Update: Partial<Database['public']['Tables']['creations']['Insert']>
      }
      luminor_bonds: {
        Row: {
          id: string
          user_id: string
          luminor_id: string
          level: number
          xp: number
          relationship_type: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['luminor_bonds']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['luminor_bonds']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
>>>>>>> 17fcd1ab4a0b2caddc8261ca1faa7cb46e36e9bc
