// Supabase Database Types - Placeholder
// This would normally be generated by supabase gen types

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          academy_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      creations: {
        Row: {
          id: string
          title: string
          description: string | null
          type: string
          media_url: string | null
          thumbnail_url: string | null
          user_id: string
          luminor_id: string | null
          visibility: string
          status: string
          tags: string[]
          likes_count: number
          comments_count: number
          views_count: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['creations']['Row'], 'id' | 'created_at' | 'updated_at' | 'likes_count' | 'comments_count' | 'views_count'>
        Update: Partial<Database['public']['Tables']['creations']['Insert']>
      }
      luminor_bonds: {
        Row: {
          id: string
          user_id: string
          luminor_id: string
          level: number
          xp: number
          relationship_type: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['luminor_bonds']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['luminor_bonds']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
