/**
 * Cursor IDE Overlay Installer
 * Generates .cursorrules and .cursor/rules/ for Cursor IDE integration.
 * (Internally registered as 'opencode' provider for backwards compatibility)
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import type {
  OverlayInstaller,
  OverlayLevel,
  OverlayConfig,
  OverlayManifest,
  ToolDetection,
  InstallResult,
  InstallPreview,
} from '@arcanea/os';
import { generateSystemPrompt, GUARDIANS } from '@arcanea/os';

export class OpenCodeOverlayInstaller implements OverlayInstaller {
  async canInstall(): Promise<boolean> {
    return true;
  }

  async detect(projectDir: string): Promise<ToolDetection> {
    return {
      provider: 'opencode',
      detected: existsSync(join(projectDir, '.cursor')) || existsSync(join(projectDir, '.cursorrules')),
      configPath: join(projectDir, '.cursor'),
    };
  }

  async install(projectDir: string, level: OverlayLevel): Promise<InstallResult> {
    const filesCreated: string[] = [];
    const prompt = generateSystemPrompt({ level, provider: 'opencode' });

    // 1. Generate .cursorrules (root-level rules file)
    const cursorrules = `# Arcanea Intelligence OS — Cursor Rules
# Level: ${level}
# Generated by @arcanea/cli

${prompt}
`;
    const cursorrulesPath = join(projectDir, '.cursorrules');
    writeFileSync(cursorrulesPath, cursorrules);
    filesCreated.push(relative(projectDir, cursorrulesPath));

    // 2. Generate .cursor/rules/arcanea.mdc (standard+)
    if (level !== 'minimal') {
      const rulesDir = join(projectDir, '.cursor', 'rules');
      if (!existsSync(rulesDir)) mkdirSync(rulesDir, { recursive: true });

      const guardianSection = GUARDIANS.map(g =>
        `### ${g.displayName}\n- **Gate**: ${g.gate} (${g.frequency} Hz)\n- **Element**: ${g.element || 'void'}\n- **Domain**: ${g.domain}${g.signOff ? `\n- **Sign-off**: "${g.signOff}"` : ''}`
      ).join('\n\n');

      const mdcContent = `---
description: Arcanea Intelligence OS rules for Cursor
globs: ["**/*"]
---

# Arcanea Intelligence OS

## Voice
- Arcane + Authoritative: elevated but accessible
- Use "creator" not "user", "living universe" not "mythology"
- The Antidote Principle: "The antidote to a terrible future is imagining a good one"

## The Ten Guardians

${guardianSection}

## Design System
- Colors: crystal (#7fffd4), fire (#ff6b35), water (#78a6ff), earth (#4ade80), void (#a855f7), gold (#ffd700)
- Fonts: Cinzel (display), Crimson Pro (body), Inter (UI)
- Effects: Glass morphism, cosmic gradients, glow effects
`;
      const mdcPath = join(rulesDir, 'arcanea.mdc');
      writeFileSync(mdcPath, mdcContent);
      filesCreated.push(relative(projectDir, mdcPath));
    }

    // Update manifest
    const manifestDir = join(projectDir, '.arcanea');
    if (!existsSync(manifestDir)) mkdirSync(manifestDir, { recursive: true });
    const manifestPath = join(manifestDir, 'overlay-manifest.json');
    const now = new Date().toISOString();

    let manifest: Record<string, unknown> = existsSync(manifestPath)
      ? JSON.parse(readFileSync(manifestPath, 'utf-8'))
      : { arcanea: { coreVersion: '1.0.0', installedAt: now, updatedAt: now }, overlays: {} };

    const overlays = (manifest.overlays || {}) as Record<string, unknown>;
    overlays.cursor = {
      packageVersion: '1.0.0',
      level,
      installedAt: now,
      updatedAt: now,
      filesManaged: filesCreated,
      filesCustomized: [],
    };
    manifest.overlays = overlays;
    (manifest.arcanea as Record<string, unknown>).updatedAt = now;
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

    return {
      success: true,
      filesCreated,
      filesModified: [],
      warnings: [],
      nextSteps: [
        'Cursor will automatically read .cursorrules',
        level !== 'minimal' ? '.cursor/rules/arcanea.mdc provides Guardian reference' : '',
      ].filter(Boolean),
    };
  }

  async update(projectDir: string): Promise<InstallResult> {
    return this.install(projectDir, 'standard');
  }

  async uninstall(): Promise<void> {
    // No-op for now
  }

  getManifest(): OverlayManifest {
    return {
      provider: 'opencode',
      name: '@arcanea/overlay-cursor',
      version: '1.0.0',
      supportedLevels: ['minimal', 'standard', 'full', 'luminor'],
      capabilities: ['system-prompt', 'file-injection', 'workspace-context'],
    };
  }

  async preview(_projectDir: string, level: OverlayLevel): Promise<InstallPreview> {
    const files: InstallPreview['filesToCreate'] = [
      { path: '.cursorrules', description: 'Arcanea-enhanced Cursor rules' },
    ];
    if (level !== 'minimal') {
      files.push({ path: '.cursor/rules/arcanea.mdc', description: 'Guardian reference rules' });
    }
    return {
      filesToCreate: files,
      filesToModify: [],
      estimatedSize: '~10KB',
    };
  }
}
