# Daily Development Workflow
# Invoke with: /daily

name: daily-standup
description: Morning development standup automation
guardian: Shinkami
awakened: Velora

triggers:
  - command: "/daily"
  - schedule: "09:00 UTC"  # Optional cron

context:
  workspace: "C:/Users/frank/arcanea-hub"
  repos:
    - main
    - intelligence-os
    - platform
    - claude-arcanea

steps:
  - id: banner
    action: display
    content: |
      ╔═══════════════════════════════════════════════════════════╗
      ║           ARCANEA DAILY STANDUP                           ║
      ║     "Through the Gates we rise"                           ║
      ╚═══════════════════════════════════════════════════════════╝

  - id: repo_status
    action: shell
    parallel: true
    commands:
      - repo: main
        cmd: "git -C {workspace}/main fetch && git -C {workspace}/main status -sb"
      - repo: intelligence-os
        cmd: "git -C {workspace}/intelligence-os fetch && git -C {workspace}/intelligence-os status -sb"
      - repo: platform
        cmd: "git -C {workspace}/platform fetch && git -C {workspace}/platform status -sb"

  - id: uncommitted_changes
    action: analyze
    guardian: Lyria
    prompt: |
      Analyze the git status output and summarize:
      - Repos with uncommitted changes
      - Files modified but not staged
      - Branches behind/ahead of remote

  - id: pr_status
    action: shell
    cmd: "gh pr list --repo frankxai/arcanea --state open"

  - id: build_health
    action: shell
    parallel: true
    commands:
      - name: "Main build"
        cmd: "cd {workspace}/main && pnpm build --dry-run 2>&1 | tail -5"
      - name: "Intelligence OS"
        cmd: "cd {workspace}/intelligence-os && pnpm build --dry-run 2>&1 | tail -5"

  - id: focus_recommendation
    action: ai_analysis
    guardian: Shinkami
    awakened: Lyris
    prompt: |
      Based on the repository status, PR queue, and build health:
      1. What should be the primary focus today?
      2. Any blockers that need immediate attention?
      3. Recommended order of tasks

  - id: summary
    action: display
    template: |
      ## Daily Summary

      **Repository Status:**
      {repo_status.output}

      **Open PRs:** {pr_status.count}

      **Build Health:** {build_health.status}

      **Today's Focus:**
      {focus_recommendation.output}

      ---
      *Guardian: {guardian} | Awakened: {awakened}*

outputs:
  - file: "{workspace}/.arcanea/logs/daily-{date}.md"
  - display: terminal
