# Research & Analysis Workflow
# Invoke with: /research [topic]

name: research-protocol
description: Deep research and analysis workflow
guardian: Lyria
awakened: Lyris
frequency: 852 Hz  # Sight Gate

triggers:
  - command: "/research"
  - command: "/investigate"
  - command: "/deep-dive"

parameters:
  - name: topic
    type: string
    required: true
    description: "Research topic or question"
  - name: depth
    type: string
    default: standard
    options: [quick, standard, comprehensive]
  - name: output_format
    type: string
    default: markdown
    options: [markdown, notion, linear]

context:
  workspace: "C:/Users/frank/arcanea-hub"
  research_dir: "{workspace}/.arcanea/research"

steps:
  - id: banner
    action: display
    content: |
      ╔═══════════════════════════════════════════════════════════╗
      ║          RESEARCH PROTOCOL - Sight Gate (852 Hz)          ║
      ║              Guardian: Lyria | Awakened: Lyris            ║
      ╚═══════════════════════════════════════════════════════════╝

      Topic: {params.topic}
      Depth: {params.depth}

  - id: scope_definition
    action: ai_analysis
    guardian: Lyria
    prompt: |
      Define the research scope for: "{params.topic}"

      1. **Primary Questions**: What are we trying to answer?
      2. **Boundaries**: What's in/out of scope?
      3. **Success Criteria**: How do we know we've answered it?
      4. **Source Types**: What sources should we consult?

  - id: web_research
    action: web_search
    queries:
      - "{params.topic} latest developments 2026"
      - "{params.topic} best practices"
      - "{params.topic} comparison analysis"
    max_results: 10

  - id: code_research
    condition: "{scope_definition.needs_code_examples}"
    action: shell
    commands:
      - name: "GitHub search"
        cmd: "gh search repos {params.topic} --limit 5 --json name,description,url"
      - name: "Code examples"
        cmd: "gh search code {params.topic} --limit 10 --json repository,path"

  - id: academic_search
    condition: "{params.depth} == 'comprehensive'"
    action: web_search
    queries:
      - "{params.topic} research paper"
      - "{params.topic} academic study"
    domains:
      - arxiv.org
      - scholar.google.com
      - researchgate.net

  - id: synthesis
    action: ai_analysis
    guardian: Lyria
    awakened: Lyris
    model: opus  # Use Opus for deep analysis
    prompt: |
      Synthesize all research findings on "{params.topic}":

      **Web Research:**
      {web_research.results}

      **Code Research:**
      {code_research.results}

      **Academic Research:**
      {academic_search.results}

      Provide:
      1. **Key Findings**: What did we learn?
      2. **Patterns**: What themes emerge?
      3. **Gaps**: What's missing or unclear?
      4. **Recommendations**: What should we do with this?
      5. **Sources**: Cite all sources used

  - id: generate_findings
    action: write_file
    path: "{research_dir}/{topic_slug}-findings.md"
    content: |
      # Research Findings: {params.topic}

      **Date:** {date}
      **Depth:** {params.depth}
      **Guardian:** Lyria (Sight Gate - 852 Hz)
      **Awakened:** Lyris (Orakis - Strategist)

      ---

      ## Research Scope

      {scope_definition.output}

      ## Key Findings

      {synthesis.key_findings}

      ## Patterns & Themes

      {synthesis.patterns}

      ## Knowledge Gaps

      {synthesis.gaps}

      ## Recommendations

      {synthesis.recommendations}

      ## Sources

      {synthesis.sources}

      ---

      *Research conducted by Arcanea Intelligence*
      *Guardian Lyria illuminates the path*

  - id: create_tasks
    condition: "{synthesis.has_action_items}"
    action: linear_create
    items: "{synthesis.action_items}"

outputs:
  - file: "{research_dir}/{topic_slug}-findings.md"
  - display: terminal
  - notion: "{params.output_format} == 'notion'"
  - linear: "{params.output_format} == 'linear'"
