codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
    after_n_builds: 2

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  hide_project_coverage: false

flags:
  unittests:
    paths:
      - tests/unit/
    carryforward: true
  integration:
    paths:
      - tests/integration/
    carryforward: true
  e2e:
    paths:
      - tests/e2e/
    carryforward: true

ignore:
  - "tests/**/*"
  - "**/node_modules/**/*"
  - "**/dist/**/*"
  - "**/build/**/*"
  - "**/.arcanea/**/*"
  - "apps/**/*"
  - "starlight-intelligence-system/**/*"
